services:
- type: web
name: cn-jobright-mvp
env: python
plan: free
region: singapore
buildCommand: "pip install -r requirements.txt"
startCommand: "python app.py"
autoDeploy: true
envVars:
- key: FLASK_ENV
value: production
- key: LLM_PROVIDER
sync: false
- key: LLM_API_KEY
sync: false
- key: LLM_BASE_URL
sync: false
- key: MODEL_NAME
sync: false
- key: SECRET_KEY
sync: false
- key: DATA_RETENTION_DAYS
sync: false
- key: MAX_JD_PER_RUN
sync: false
- key: MAX_TOKENS_PER_CALL
sync: false
- key: TEMPERATURE
sync: false
